server:
  port: 9001

spring:
  application:
    name: nacos-cloudalibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.1.16:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"