server:
  port: 8083

spring:
  application:
    name: nacos-cloudalibaba--consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.1.16:8848

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-cloudalibaba-provider